name: execute kolla build

on: push

jobs:
  build_containers:
    runs-on: ubuntu-latest
    steps:
      - name: build doni containers
        uses: ChameleonCloud/ciab-build-action@main
        with:
          config_set: x86_ubuntu
          kolla_build_profile: doni
          push: no
