name: execute kolla build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ChameleonCloud/kolla-containers
          event-type: doni-build
          client-payload: |
            '{
              "kolla_build_profile": "doni",
              "push": "yes",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
            }'
