name: execute kolla build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ci
          repo: ChameleonCloud/kolla-containers
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          inputs: '{"kolla_build_profile": "doni", "push": "yes", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}",}'
